name: just_audio_example
description: Demonstrates how to use the just_audio plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_session: ^0.1.21
  rxdart: ^0.28.0
  just_audio:
    path: ../../just_audio
  just_audio_background:
    path: ..

# Uncomment when testing platform interface changes.
# dependency_overrides:
#   just_audio_platform_interface:
#     path: ../../just_audio_platform_interface
#   just_audio_web:
#     path: ../../just_audio_web

dev_dependencies:
  # TODO: uncomment these dependencies when they have nullsafe versions.
  # flutter_driver:
  #   sdk: flutter
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  # integration_test: ^1.0.1
  test: ^1.16.5

dependency_overrides:
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

flutter:
  uses-material-design: true

  assets:
    - audio/
