name: just_audio_background
description: An add-on for just_audio that supports background playback and media notifications.
homepage: https://github.com/ryanheise/just_audio/tree/master/just_audio_background
version: 0.0.1-beta.13
publish_to: none
topics:
  - audio
  - sound
  - player
  - background

dependencies:
  just_audio_platform_interface:
    git: https://github.com/kumsumit/just_audio_platform_interface.git
  # just_audio_platform_interface:
  #   path: ../just_audio_platform_interface
  audio_service: ^0.18.15
  audio_session: ^0.1.21
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.15.0
  rxdart: '>=0.28.0 <0.29.0'

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
dependency_overrides:
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
